name: tool_sfera_validator
description: "Tool to validate SFERA test data"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.9.2

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  # workspace
  sfera: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
